name: Feature request
title: "[Feature]"
description: Propose your feature request

body:
  - type: markdown
    attributes:
      value: |
        ## Before submitting an issue, please confirm the following:
        1. The issue title should be concise and clear. The title format should be similar to: [Feature][Windows] Support startup on system boot.
        2. Please ensure that no one has submitted a similar issue in the [Existing Issues] section. Otherwise, please discuss it under an existing issue.
        3. Please be sure to describe the problem in detail according to the template specifications. Otherwise, the issue will be closed directly.

  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: A clear and concise description of what the feature is
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use case
      description: Please describe the use case of your feature request
    validations:
      required: true
  - type: checkboxes
    id: os-labels
    attributes:
      label: Target OS
      description: Please select the operating system(s) for this feature request
      options:
        - label: Android
        - label: Windows
        - label: macOS
    validations:
      required: true
